#!/usr/bin/python
# -*- coding: utf-8 -*-

import pprint

f = open('/usr/share/X11/rgb.txt', 'r')
lines = f.readlines()
tokens = [x.split(None, 3) for x in lines]
convert = lambda x: hex(int(x))[2:]
items = [(name[:-1].lower(), (convert(r),convert(g),convert(b))) for (r,g,b,name) in tokens]
d = dict(items)

# Overwrite some colors which differs from x11 rgb.txt
d['gray']   = ('7f', '7f', '7f')
d['green']  = ('00', '7f', '00')
d['maroon'] = ('7f', '00', '00')
d['purple'] = ('7f', '00', '7f')

print '#!/usr/bin/python'
print '# -*- coding: utf-8 -*-'
print
print '# autogenerated from X11/rgb.txt'
print 'names = \\'
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(d)
