#!/usr/bin/python
# -*- coding: utf-8 -*-

import pprint

f = open('/usr/share/X11/rgb.txt', 'r')
lines = f.readlines()
tokens = [x.split(None, 3) for x in lines]
convert = lambda x: hex(int(x))[2:]
items = [(name[:-1].lower(), (convert(r),convert(g),convert(b))) for (r,g,b,name) in tokens]

print '#!/usr/bin/python'
print '# -*- coding: utf-8 -*-'
print
print '# autogenerated from X11/rgb.txt'
print 'names = \\'
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(dict(items))
